sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 113769028a
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8xWBECmhf8FpnjYrrH
    access-key-secret: ppNMV9AVOtyEPj1BOEOydE9NMT355P
    bucket-name: cang-qiong-take-out1
  redis:
    host: localhost
    port: 6379
    password: 113769028a
    database: 0
  wechat:
    appid: wx6f6c0ab68f780d97
    secret: 3b710bad1120ca744aa01b0e907dd932